"""MSOS Autobuilder public package surface."""

from .backends import (
    CodexCliBackend,
    CodexHostError,
    CodexSandboxMode,
    GitWorkspaceError,
    LocalGitCloneBackend,
    LocalProcessBackend,
    ProcessExecutionError,
)
from .codex_shadow import (
    CodexConfigError,
    CodexHostConfig,
    CodexPreflightReport,
    CodexShadowError,
    CodexShadowReport,
    ShadowTaskSpec,
    codex_host_preflight,
    load_codex_host_config,
    load_codex_shadow_manifest,
    run_codex_shadow,
)
from .contracts import ProductContract, load_product_contract
from .lanes import (
    LaneConflictError,
    LaneScopeError,
    assert_changed_paths_allowed,
    assert_lanes_compatible,
)
from .leases import FileLeaseStore, LeaseConflictError, LeaseRecord, LeaseStateError
from .models import BuildLane, BuildTask, CostClass, WorkerCapabilities
from .persistent_host import (
    GitJobFeedConfig,
    HostJob,
    HostJobError,
    HostLockError,
    HostPaths,
    HostRunResult,
    HostStatus,
    JobFeedError,
    PersistentHost,
    PersistentHostConfig,
    PersistentHostConfigError,
    approve_pending_job,
    enqueue_manifest,
    load_persistent_host_config,
    parse_host_job,
    sync_git_job_feed,
)
from .process_witness import ProcessWitnessReport, run_process_witness
from .routing import BackendRouter, BackendRoutingError
from .scheduler import ParallelScheduler, SchedulerError
from .workspace_witness import WorkspaceWitnessReport, run_workspace_witness
from .workspaces import WorkspaceIsolationError, WorkspacePolicy

__all__ = [
    "BackendRouter",
    "BackendRoutingError",
    "BuildLane",
    "BuildTask",
    "CodexCliBackend",
    "CodexConfigError",
    "CodexHostConfig",
    "CodexHostError",
    "CodexPreflightReport",
    "CodexSandboxMode",
    "CodexShadowError",
    "CodexShadowReport",
    "CostClass",
    "FileLeaseStore",
    "GitJobFeedConfig",
    "GitWorkspaceError",
    "HostJob",
    "HostJobError",
    "HostLockError",
    "HostPaths",
    "HostRunResult",
    "HostStatus",
    "JobFeedError",
    "LaneConflictError",
    "LaneScopeError",
    "LeaseConflictError",
    "LeaseRecord",
    "LeaseStateError",
    "LocalGitCloneBackend",
    "LocalProcessBackend",
    "ParallelScheduler",
    "PersistentHost",
    "PersistentHostConfig",
    "PersistentHostConfigError",
    "ProcessExecutionError",
    "ProcessWitnessReport",
    "ProductContract",
    "SchedulerError",
    "ShadowTaskSpec",
    "WorkerCapabilities",
    "WorkspaceIsolationError",
    "WorkspacePolicy",
    "WorkspaceWitnessReport",
    "approve_pending_job",
    "assert_changed_paths_allowed",
    "assert_lanes_compatible",
    "codex_host_preflight",
    "enqueue_manifest",
    "load_codex_host_config",
    "load_codex_shadow_manifest",
    "load_persistent_host_config",
    "load_product_contract",
    "parse_host_job",
    "run_codex_shadow",
    "run_process_witness",
    "run_workspace_witness",
    "sync_git_job_feed",
]
